package com.pedaerial.operatorflightcheck.entity;

public enum JobType {
    INSURANCE_INSPECTION,
    ROOF_SURVEY,
    REAL_ESTATE,
    MAPPING,
    CONSTRUCTION,
    OTHER,
    AERIAL_PHOTOGRAPHY,
    AERIAL_VIDEOGRAPHY,
    THERMAL_INSPECTION,
    SURVEYING_ORTHOMOSAIC,
    SURVEYING_3D_MODEL,
    EVENT_COVERAGE,
    CELL_TOWER_INSPECTION,
    SOLAR_PANEL_INSPECTION
}
