version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  pre_build:
    commands:
      - cd backend
      - mvn -q -DskipTests compile
      - cd ../frontend
      - npm ci
  build:
    commands:
      - npm run build
      - cd ../backend
      - mvn test
      - mvn package -DskipTests
artifacts:
  files:
    - backend/target/*.jar
    - frontend/dist/**/*
  discard-paths: no
