-- Deprecated legacy demo SQL.
-- The current application seeds demo users, jobs, invoices, payments, reports,
-- and placeholder deliverables through DemoDataConfig when the "demo" profile is active.
