export const mockForecast = [
  {
    day: "Mon",
    date: "Mar 24",
    windMph: 8,
    gustMph: 11,
    precipPct: 4,
    severeWeather: false,
  },
  {
    day: "Tue",
    date: "Mar 25",
    windMph: 10,
    gustMph: 14,
    precipPct: 8,
    severeWeather: false,
  },
  {
    day: "Wed",
    date: "Mar 26",
    windMph: 14,
    gustMph: 20,
    precipPct: 18,
    severeWeather: false,
  },
  {
    day: "Thu",
    date: "Mar 27",
    windMph: 22,
    gustMph: 29,
    precipPct: 42,
    severeWeather: true,
  },
  {
    day: "Fri",
    date: "Mar 28",
    windMph: 15,
    gustMph: 21,
    precipPct: 26,
    severeWeather: false,
  },
  {
    day: "Sat",
    date: "Mar 29",
    windMph: 11,
    gustMph: 15,
    precipPct: 10,
    severeWeather: false,
  },
  {
    day: "Sun",
    date: "Mar 30",
    windMph: 13,
    gustMph: 19,
    precipPct: 21,
    severeWeather: false,
  },
];
