export const mockDroneProfiles = [
  {
    id: "micro-1",
    name: "Mini 4 Pro",
    type: "Micro",
    addOns: ["ND filter", "Landing pad", "Strobe beacon"],
    windGreenMph: 10,
    windYellowMph: 15,
    gustGreenMph: 14,
    gustYellowMph: 20,
    precipGreenPct: 10,
    precipYellowPct: 25,
  },
  {
    id: "prosumer-1",
    name: "DJI Air 3",
    type: "Prosumer",
    addOns: ["ND filter", "Prop guard set", "Remote monitor hood"],
    windGreenMph: 12,
    windYellowMph: 18,
    gustGreenMph: 16,
    gustYellowMph: 24,
    precipGreenPct: 12,
    precipYellowPct: 30,
  },
  {
    id: "heavy-1",
    name: "Matrice 350",
    type: "Heavy",
    addOns: ["Spotlight", "Loudspeaker", "Thermal payload"],
    windGreenMph: 16,
    windYellowMph: 24,
    gustGreenMph: 22,
    gustYellowMph: 30,
    precipGreenPct: 15,
    precipYellowPct: 35,
  },
];
