export const mockHourlyForecast = {
  Mon: [
    { time: "7 AM", windMph: 6, gustMph: 9, precipPct: 2, severeWeather: false },
    { time: "9 AM", windMph: 7, gustMph: 10, precipPct: 3, severeWeather: false },
    { time: "11 AM", windMph: 8, gustMph: 11, precipPct: 4, severeWeather: false },
    { time: "1 PM", windMph: 9, gustMph: 12, precipPct: 4, severeWeather: false },
    { time: "3 PM", windMph: 10, gustMph: 13, precipPct: 6, severeWeather: false },
    { time: "5 PM", windMph: 9, gustMph: 12, precipPct: 5, severeWeather: false },
  ],
  Tue: [
    { time: "7 AM", windMph: 8, gustMph: 12, precipPct: 5, severeWeather: false },
    { time: "9 AM", windMph: 9, gustMph: 13, precipPct: 5, severeWeather: false },
    { time: "11 AM", windMph: 10, gustMph: 14, precipPct: 8, severeWeather: false },
    { time: "1 PM", windMph: 11, gustMph: 15, precipPct: 9, severeWeather: false },
    { time: "3 PM", windMph: 12, gustMph: 16, precipPct: 10, severeWeather: false },
    { time: "5 PM", windMph: 10, gustMph: 14, precipPct: 8, severeWeather: false },
  ],
  Wed: [
    { time: "7 AM", windMph: 11, gustMph: 16, precipPct: 10, severeWeather: false },
    { time: "9 AM", windMph: 13, gustMph: 18, precipPct: 12, severeWeather: false },
    { time: "11 AM", windMph: 14, gustMph: 20, precipPct: 18, severeWeather: false },
    { time: "1 PM", windMph: 15, gustMph: 22, precipPct: 20, severeWeather: false },
    { time: "3 PM", windMph: 16, gustMph: 23, precipPct: 22, severeWeather: false },
    { time: "5 PM", windMph: 14, gustMph: 21, precipPct: 17, severeWeather: false },
  ],
  Thu: [
    { time: "7 AM", windMph: 18, gustMph: 24, precipPct: 30, severeWeather: true },
    { time: "9 AM", windMph: 20, gustMph: 27, precipPct: 36, severeWeather: true },
    { time: "11 AM", windMph: 22, gustMph: 29, precipPct: 42, severeWeather: true },
    { time: "1 PM", windMph: 24, gustMph: 31, precipPct: 46, severeWeather: true },
    { time: "3 PM", windMph: 23, gustMph: 30, precipPct: 44, severeWeather: true },
    { time: "5 PM", windMph: 21, gustMph: 28, precipPct: 38, severeWeather: true },
  ],
  Fri: [
    { time: "7 AM", windMph: 13, gustMph: 18, precipPct: 18, severeWeather: false },
    { time: "9 AM", windMph: 14, gustMph: 19, precipPct: 20, severeWeather: false },
    { time: "11 AM", windMph: 15, gustMph: 21, precipPct: 26, severeWeather: false },
    { time: "1 PM", windMph: 16, gustMph: 22, precipPct: 28, severeWeather: false },
    { time: "3 PM", windMph: 16, gustMph: 23, precipPct: 30, severeWeather: false },
    { time: "5 PM", windMph: 14, gustMph: 20, precipPct: 24, severeWeather: false },
  ],
  Sat: [
    { time: "7 AM", windMph: 8, gustMph: 11, precipPct: 6, severeWeather: false },
    { time: "9 AM", windMph: 9, gustMph: 12, precipPct: 7, severeWeather: false },
    { time: "11 AM", windMph: 11, gustMph: 15, precipPct: 10, severeWeather: false },
    { time: "1 PM", windMph: 12, gustMph: 16, precipPct: 11, severeWeather: false },
    { time: "3 PM", windMph: 11, gustMph: 15, precipPct: 9, severeWeather: false },
    { time: "5 PM", windMph: 10, gustMph: 14, precipPct: 8, severeWeather: false },
  ],
  Sun: [
    { time: "7 AM", windMph: 10, gustMph: 14, precipPct: 12, severeWeather: false },
    { time: "9 AM", windMph: 11, gustMph: 16, precipPct: 15, severeWeather: false },
    { time: "11 AM", windMph: 13, gustMph: 18, precipPct: 21, severeWeather: false },
    { time: "1 PM", windMph: 14, gustMph: 19, precipPct: 22, severeWeather: false },
    { time: "3 PM", windMph: 13, gustMph: 19, precipPct: 20, severeWeather: false },
    { time: "5 PM", windMph: 12, gustMph: 17, precipPct: 18, severeWeather: false },
  ],
};
