-- Deprecated legacy seed file.
-- Demo data is now created by:
-- backend/src/main/java/com/pedaerial/operatorflightcheck/config/DemoDataConfig.java
-- Run the backend with the "demo" Spring profile to seed the current data model.
